### PR TITLE
Energy Distribution algorithm implementations

### PR DESCRIPTION
**Pull request by jdaymude**
Adds an implementation of the Energy-Sharing algorithm and its composition with Hexagon Formation described [here](https://arxiv.org/abs/2007.04377).

### CODE REVIEW

**Review by nobleharasha — COMMENTED** [review]
Everything is working perfectly for the most part, these are just a couple of tiny instances of behavior that may not be fully expected or desired:

1. For the Energy + Hexagon algorithm, the simulator seems to crash with holeProb values that are approximately 0.7 and more.

2. For the Energy Sharing algorithm, the usage parameter (which is defined as only being 0 or 1) accepts all values in (-1, 2) without outputting an error. 
usage = 1 yields the reproduction mode, as expected, and all of the other values in (-1, 2) that aren't 1 yield the invisible actions mode.

3. For the Energy + Hexagon algorithm, the the parameter transferRate is listed as such in both the code and documentation (API). However, this parameter is listed as "Harvest Rate" in the UI. I'm assuming that this is purposeful and not an issue at all, but I figured I would at least point out the discrepancy in case it was indeed a typo, etc.

**Comment by jdaymude** [comment]
@nharasha1202, in response to what you found:

> For the Energy + Hexagon algorithm, the simulator seems to crash with holeProb values that are approximately 0.7 and more.

This turned out to be a pretty major issue related to the random tree instantiation algorithm that we use in many system constructors (leader election, shape formation, etc.). I've opened a separate issue (#48) to fix it, since it isn't specific to the energy distribution algorithms.

> For the Energy Sharing algorithm, the usage parameter (which is defined as only being 0 or 1) accepts all values in (-1, 2) without outputting an error. `usage = 1` yields the reproduction mode, as expected, and all of the other values in (-1, 2) that aren't 1 yield the invisible actions mode.

It's actually much worse than this, as it turns out. When the "Instantiate" button is pressed, the ParameterListModel parses the parameters (passed in as strings) according to the data types specified by the users. For `usage`, it gets parsed as `params[1].toInt()`. The way `toInt()` is implemented, it essentially takes *any* decimal number and just maps it to `0`. So in fact, if you input any decimal value whatsoever for `usage`, it will be treated as `usage = 0` by the time it hits the `instantiate()` function. This is why you keep seeing the invisible actions mode popping up. Unfortunately, there's no easy fix for this one. I'm choosing to leave it as is, since it doesn't exactly force undefined behavior. If it becomes an issue, we could change `usage` from an integer to a string (e.g., `"u"` for uniform and `"r"` for reproduction).

> For the Energy + Hexagon algorithm, the the parameter transferRate is listed as such in both the code and documentation (API). However, this parameter is listed as "Harvest Rate" in the UI. I'm assuming that this is purposeful and not an issue at all, but I figured I would at least point out the discrepancy in case it was indeed a typo, etc.

Fixed.

**Review by jwweber — CHANGES_REQUESTED** [review]
Change request: Add multiple roots parameter for basic energy sharing algorithm

**Review by jwweber — APPROVED** [review]
lgtm

**Review by nobleharasha — APPROVED** [review]
LGTM.

**Review by jwweber — APPROVED** [review]
lgtm

**Pull request merged**
