### PR TITLE
Parameter list bug fix

### PR DESCRIPTION
**Pull request by nobleharasha**
Fixes bug in which the parameter list fails to render upon starting simulator.

### CODE REVIEW

**Comment by jdaymude** [comment]
Resolves #1.

**Review by jdaymude — DISMISSED** [review]
LGTM.

**Comment by jdaymude** [comment]
@josephbriones please test this out on macOS and approve if everything looks good.

**Review by jdaymude — APPROVED** [review]
Rebased onto `dev`, LGTM.

**Review by josephbriones — APPROVED** [review]
LGTM

**Review by josephbriones — APPROVED** [review]
LGTM

**Pull request merged**
