### PR TITLE
Allow removal of particles at runtime

### PR DESCRIPTION
**Pull request by jdaymude**
Adds functionality for removing particles at runtime in the form of a new `AmoebotSystem::remove(AmoebotParticle* particle)` function. This complements the existing `AmoebotSystem::insert(AmoebotParticle* particle)` function.

Notably, this requires a reimplementation and reordering of operations in `AmoebotSystem::activate()`. Otherwise, the system will try to register an activation for a now potentially nonexistent particle.

To illustrate the dynamic addition and removal of particles at runtime, this PR also adds a `DynamicDemo` tutorial.

### CODE REVIEW

**Comment by jdaymude** [comment]
@nharasha1202 Please handle the Windows testing; I'll take care of macOS.

**Comment by jdaymude** [comment]
Tested successfully on macOS.

**Review by nobleharasha — COMMENTED** [review]
If the entire system dies and the simulation therefore terminates, pressing the Start button once more causes AmoebotSim to crash. Other terminating algorithms do not crash AmoebotSim in the same situation. The DynamicDemo tutorial does provide a warning that further instructions to removed particles can cause crashes (also, pressing start after termination is not expected user behavior), so this may not be an issue to resolve. Besides this, LGTM.

**Comment by jdaymude** [comment]
@nharasha1202 Thanks for catching that issue. It's now fixed, so users can press "Start" (or do the equivalent in scripting) on an empty system without crashing. AmoebotSim will now detect that there are no particles and skip the activation. The algorithm's `hasTermianted()` function is still responsible for ending the simulation.

**Review by nobleharasha — APPROVED** [review]
LGTM.

**Pull request merged**
